# run below command to process everything
# ergogen .
# npx @jscad/cli@1 output/cases/case.jscad -of stla
# ergogen . && for i in output/cases/*.jscad; do echo "$i"; npx @jscad/cli@1 "$i" -of stla; done

units:
  # default unit is mm

  # Proxy Spacing Variables
  # Kailh Choc keys are 18mm wide and 17mm tall
  kx: cx
  ky: cy
  $default_width: cx
  $default_height: cy

  # Cherry MX keys are 19mm x 19mm
  #kx: u
  #ky: u

  # Padding Variables
  px: kx + 4
  py: ky + 4

  # Defaults to M2 screws
  screwSize: 1.5

points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor.shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky.key:
          column_net: P115
        ring.key:
          stagger: 12.5
          column_net: P113
        middle.key:
          stagger: 5
          column_net: P111
        index.key:
          stagger: -5
          column_net: P010
        inner.key:
          stagger: -3
          column_net: P009
        inner2:
          rows:
            top.skip: true
            num.skip: true
          key:
            column_net: P106
            spread: 1kx + 1
      rows:
        bottom.row_net: P022
        home.row_net: P024
        top.row_net: P100
        num.row_net: P011
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_bottom
        shift: [-1kx, -1ky]
      columns:
        outer2.key:
          column_net: P111
        outer.key:
          column_net: P010
        home.key:
          splay: -15
          shift: [3, -2]
          column_net: P009
        inner.key:
          splay: -15
          shift: [6, -3]
          column_net: P106
      rows.cluster.row_net: P104

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  board:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        # Top left
        - ref: matrix_pinky_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]

        # Top Right
        - ref: matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner2_home
          shift: [0.5px, 2.2py]
        - ref: matrix_inner2_home
          shift: [0.5px, 0.5py]

        # Thumbs
        - ref: thumbs_inner_cluster
          shift: [0.5px, 0.5py]
        - ref: thumbs_inner_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_outer2_cluster
          shift: [-0.5px, -0.5py]

        # Bottom Left
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
  xlBoard:
    - name: board
      operation: stack
      expand: 2
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5, ky-0.5]
  mcu:
    - what: rectangle
      where:
        ref: matrix_inner_top
        shift: [19, 10]
      size: [18, 34]
  screen:
    - what: rectangle
      where:
        ref: matrix_inner_top
        shift: [19, 10]
      size: [14, 36]
  combo:
    - name: board
    - operation: subtract
      name: keys
  mounting:
    - what: circle
      radius: screwSize
      where:
        ref: matrix_pinky_num
        shift: [0, 12]
    - what: circle
      radius: screwSize
      where:
        ref: matrix_pinky_bottom
        shift: [12, -9]
    - what: circle
      radius: screwSize
      where:
        ref: matrix_inner_num
        shift: [7, 11]
    - what: circle
      radius: screwSize
      where:
        ref: matrix_inner2_bottom
        shift: [16, -12] # TODO not lining up
  standoff:
    - name: mounting
      operation: stack
      expand: 1.66
  switches:
    - what: rectangle
      where: true
      bound: false
      size: [13.8, 13.8]
  topCutout:
    - name: board
    - operation: subtract
      name: switches
    - operation: subtract
      name: mounting
    - operation: subtract
      name: screen

pcbs: # TODO add keycap outlines?
  sweeppp:
    outlines.main.outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust.shift: [0, -5]
      nice_nano:
        what: nice_nano
        params.orientation: up
        where:
          ref: matrix_inner_top
          shift: [19, 10]
          rotate: -90
      nice_view:
        what: nice_view
        params:
          side: F
          SDA: P017 # can be on any high frequency pin
          SCL: P020 # can be on any high frequency pin
          CS: P002
        where:
          ref: matrix_inner_top
          shift: [19, -8]
          rotate: 90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_inner_num
          shift: [0, 12]
          rotate: -6.7
      powerSwitch:
        what: slider
        where:
          ref: matrix_index_num
          shift: [0, 12]
          rotate: -6.7
        params:
          from: RAW
          to: BAT
      # TODO which orientation should this be in?
      jstph: # this may not be needed
        what: jstph
        where:
          ref: matrix_middle_bottom
          shift: [0, -11]
          #rotate: 180
        params:
          pos: BAT
          neg: GND
      # Mounting Holes
      holeTopLeft:
        what: mountinghole
        where:
          ref: matrix_pinky_num
          shift: [0, 12]
      holeBottomLeft:
        what: mountinghole
        where:
          ref: matrix_pinky_bottom
          shift: [12, -9]
      holeTopRight:
        what: mountinghole
        where:
          ref: matrix_inner_num
          shift: [7, 11]
      holeBottomRight:
        what: mountinghole
        where:
          ref: matrix_inner2_bottom
          shift: [16, -12] # TODO not lining up

cases:
  _bottom:
    - name: board
      extrude: 1
  _xlBottom:
    - name: xlBoard
      extrude: 1
  _outerWall:
    - name: xlBoard
      extrude: 4
  _innerWall:
    - name: board
      extrude: 4
  _wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: 4
  _standoffs:
    - name: standoff
      extrude: 4
  caseBottom:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: _xlBottom
      operation: add
    - what: case
      name: _wall
      operation: add
  # TODO space cut out for screen but may need to be higher?
  caseTop:
    - name: topCutout
      extrude: 1
